In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
dataset = pd.read_csv('data.csv')

In [5]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
x = dataset[['Country','Age','Salary']].values

In [7]:
y = dataset[['Purchased']]

In [8]:
y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [9]:
# Cleaning the data and filling the missing terms

In [10]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [11]:
imputer = imputer.fit(x[:,1:3])

In [12]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [13]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
# Converting the alphabetical data into numerical

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_x = LabelEncoder()

In [17]:
x[:,0] = label_x.fit_transform(x[:,0])

In [18]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [19]:
# So this method has a problem as the numbers assigned to the countires does not have a meaning but the machine learning
#model can make some meaning out of it.

In [20]:
# So we will use this another 0 and 1 method to convert then into numbers 

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
onehotencoder = OneHotEncoder()

In [23]:
x = onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [24]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [25]:
# Now this data will tell the country.

In [26]:
# Now to convert the purchased section to numeric values

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
label_p = LabelEncoder()

In [29]:
y = label_p.fit_transform(y)

C:\Users\Prakhar Jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [30]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [31]:
# We used Label Encoder method to convery Yes and No into 1 and 0

In [32]:
# Now we will split the data for training and Testing 

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
print(x_train)
print(y_train)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]
[1 1 1 0 1 0 0 1]


In [36]:
#Now we will use Standard Scalar to reduce the variations of a feature if any so that the feature will not have very distinct values

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scx = StandardScaler()

In [39]:
x_train = scx.fit_transform(x_train)

In [40]:
x_test = scx.transform(x_test)

In [41]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

In [42]:
# Now the data is ready for Machine Learning